apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgresql/sealed-secret.yaml
- postgresql/postgresql.yaml
- redis/redis.yaml
- rabbitmq/sealed-secret.yaml
- rabbitmq/rabbitmq.yaml