apiVersion: v1
kind: ConfigMap
metadata:
  name: jpstudy-app-dev-config
data:
  FRONTEND_URI: https://jpstudy.org
  POSTGRES_URL: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/jpstudy
  DDL: "false"
  FLYWAY_ENABLED: "true"
  CLOUDFLARE_BUCKET_NAME: jpstudy