apiVersion: v1
kind: ConfigMap
metadata:
  name: jpstudy-app-config
data:
  FRONTEND_URI: "https://jpstudy.org"
  BACKEND_URI: "https://api.jpstudy.org"
  POSTGRES_URL: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/jpstudy
  REDIS_HOST: redis.database.svc.cluster.local
  DDL: none
  FLYWAY_ENABLED: "true"
  CLOUDFLARE_BUCKET_NAME: jpstudy
  CORS_ALLOWED_ORIGINS: "https://jpstudy.org,https://infra-admin.jpstudy.org"